#!/bin/bash
# mysql公式イメージが初回起動時にのみ実行するブートストラップスクリプト。
# expense-api / urlshortener-api 用にDBとユーザーをそれぞれ分離して作成する。
set -euo pipefail

mysql -uroot -p"${MYSQL_ROOT_PASSWORD}" <<-SQL
  CREATE DATABASE IF NOT EXISTS \`${APP_EXPENSE_DB}\` CHARACTER SET utf8mb4;
  CREATE USER IF NOT EXISTS '${APP_EXPENSE_USER}'@'%' IDENTIFIED BY '${APP_EXPENSE_PASSWORD}';
  GRANT ALL PRIVILEGES ON \`${APP_EXPENSE_DB}\`.* TO '${APP_EXPENSE_USER}'@'%';

  -- RSpecをローカルのコンテナ内で実行するためのテスト用DB (Railsは接続先DB名に _test を付ける)
  CREATE DATABASE IF NOT EXISTS \`${APP_EXPENSE_DB}_test\` CHARACTER SET utf8mb4;
  GRANT ALL PRIVILEGES ON \`${APP_EXPENSE_DB}_test\`.* TO '${APP_EXPENSE_USER}'@'%';

  CREATE DATABASE IF NOT EXISTS \`${APP_SHORTENER_DB}\` CHARACTER SET utf8mb4;
  CREATE USER IF NOT EXISTS '${APP_SHORTENER_USER}'@'%' IDENTIFIED BY '${APP_SHORTENER_PASSWORD}';
  GRANT ALL PRIVILEGES ON \`${APP_SHORTENER_DB}\`.* TO '${APP_SHORTENER_USER}'@'%';

  CREATE DATABASE IF NOT EXISTS \`${APP_CONTACT_DB}\` CHARACTER SET utf8mb4;
  CREATE USER IF NOT EXISTS '${APP_CONTACT_USER}'@'%' IDENTIFIED BY '${APP_CONTACT_PASSWORD}';
  GRANT ALL PRIVILEGES ON \`${APP_CONTACT_DB}\`.* TO '${APP_CONTACT_USER}'@'%';

  FLUSH PRIVILEGES;

  -- contact-app はマイグレーションの仕組みを持たないため、ここでテーブルを作る
  USE \`${APP_CONTACT_DB}\`;
  CREATE TABLE IF NOT EXISTS contact_messages (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(255) NOT NULL,
    message TEXT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
SQL
